cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^detail/$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^submit/$', views.CartSubmit, name='CartSubmit')

]

myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^cupons/', include('cupons.urls', namespace='cupon')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^', include('shop.urls', namespace='shop'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Количество")
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.conf import settings
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from cupons.forms import CuponApllyForm


@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('cart:CartDetail')

def CartSubmit(request):
    cart = Cart(request)

    product_list = cart.get_email_values()
    context = {
        'product_list': product_list
    }
    message = render_to_string('cart/order_email.html', context)
    subject, from_email, to_emails = "New order", settings.EMAIL_HOST_USER, ["frozmanik@gmail.com"]
    email = EmailMessage(subject, message, to=to_emails, from_email=from_email)
    email.content_subtype = 'html'
    email.send()
    cart.clear()
    return redirect('cart:CartDetail')

def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')

def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    cupon_apply_form = CuponApllyForm()
    return render(request, 'cart/detail.html',
                 {'cart': cart, 'cupon_apply_form': cupon_apply_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}

{% block title %}
  Your cart
{% endblock %}

{% block content %}
  <h1>Your cart</h1>
  <table class="table-cart" >

    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td class="cart-img">
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" class="img-responsive" />
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                {% csrf_token %}
                <input type="submit" value="refresh">
              </form>
            </td>
            <td><a href="{% url "cart:CartRemove" product.id %}">Remove</a></td>
            <td class="num">{{ item.price }} €.</td>
            <td class="num">{{ item.total_price }} €.</td>
          </tr>
        {% endwith %}
      {% endfor %}


    </tbody>
  </table>

<form action="{% url 'cart:CartSubmit' %}" method="post">
  {% csrf_token %}
  <p class="text-right">
    <a href="{% url "shop:ProductList"%}" class="btn btn-light">Continue ordering</a>
    <input type="submit" value="Proceed order" id="submit1">
  </p>
</form>
{% endblock %}

cart/templates/cart/order_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>New order:</h2>
<table>
    <tbody>
    {% for product in product_list %}
    <tr>
        <td>{{product.product_name}}</td>
        <td>{{product.price}}</td>
        <td>{{product.quantity}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>